package sewakamarwahyudi;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahyudi codeplacebo
 */
public class sewakamarwahyudi extends javax.swing.JFrame {
    int hrgsewa = 0;
    int ttlbayar =0;
    int pilih =0;
    String fasilitas;
        
    /**
     * Creates new form 
     */
    public sewakamarwahyudi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alamatpenyewa = new javax.swing.JTextField();
        namapenyewa = new javax.swing.JTextField();
        tahunan = new javax.swing.JRadioButton();
        bulanan = new javax.swing.JRadioButton();
        periodebayar = new javax.swing.JComboBox();
        kipasangin = new javax.swing.JCheckBox();
        ac = new javax.swing.JCheckBox();
        magiccom = new javax.swing.JCheckBox();
        televisi = new javax.swing.JCheckBox();
        dispenser = new javax.swing.JCheckBox();
        jumlah = new javax.swing.JTextField();
        btnnew = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("WAHYUDI SEWA KAMAR");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 170, 60);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nama Penyewa :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 70, 130, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Alamat Penyewa :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 110, 140, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Periode Sewa :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 150, 120, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Periode Bayar :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 190, 120, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Fasilitas Tambahan :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 230, 160, 30);

        alamatpenyewa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alamatpenyewa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(alamatpenyewa);
        alamatpenyewa.setBounds(220, 110, 250, 30);

        namapenyewa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        namapenyewa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        namapenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapenyewaActionPerformed(evt);
            }
        });
        getContentPane().add(namapenyewa);
        namapenyewa.setBounds(220, 70, 250, 30);

        buttonGroup1.add(tahunan);
        tahunan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tahunan.setText("Tahunan");
        tahunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunanActionPerformed(evt);
            }
        });
        getContentPane().add(tahunan);
        tahunan.setBounds(380, 150, 90, 23);

        buttonGroup1.add(bulanan);
        bulanan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bulanan.setText("Bulanan");
        bulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulananActionPerformed(evt);
            }
        });
        getContentPane().add(bulanan);
        bulanan.setBounds(220, 150, 90, 23);

        periodebayar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        periodebayar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "~~ Silahkan Pilih ~~", "1 Bulan", "3 Bulan", "6 Bulan" }));
        periodebayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodebayarActionPerformed(evt);
            }
        });
        getContentPane().add(periodebayar);
        periodebayar.setBounds(220, 190, 250, 21);

        kipasangin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kipasangin.setText("Kipas Angin");
        kipasangin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kipasanginActionPerformed(evt);
            }
        });
        getContentPane().add(kipasangin);
        kipasangin.setBounds(280, 230, 110, 23);

        ac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ac.setText("AC");
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        getContentPane().add(ac);
        ac.setBounds(220, 230, 50, 23);

        magiccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        magiccom.setText("Magic Com");
        magiccom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magiccomActionPerformed(evt);
            }
        });
        getContentPane().add(magiccom);
        magiccom.setBounds(350, 260, 110, 30);

        televisi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        televisi.setText("Televisi");
        televisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                televisiActionPerformed(evt);
            }
        });
        getContentPane().add(televisi);
        televisi.setBounds(390, 230, 67, 23);

        dispenser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dispenser.setText("Dispenser");
        dispenser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispenserActionPerformed(evt);
            }
        });
        getContentPane().add(dispenser);
        dispenser.setBounds(240, 260, 110, 23);

        jumlah.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jumlah);
        jumlah.setBounds(70, 360, 400, 40);

        btnnew.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        getContentPane().add(btnnew);
        btnnew.setBounds(400, 420, 70, 40);

        btntotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btntotal.setText("Biaya Sewa");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });
        getContentPane().add(btntotal);
        btntotal.setBounds(70, 300, 400, 40);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-90, 0, 630, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulananActionPerformed
        if (bulanan.isSelected() ==true){
            pilih = 2;
            periodebayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{ "~~~Silahkan Pilih~~~","1 Bulan","3 Bulan","6 Bulan"}));
        }                                        
   
    }//GEN-LAST:event_bulananActionPerformed
    private void pesankosong(){
        JOptionPane.showMessageDialog(null, "Pesanan tidak boleh kosong!","Warning!", JOptionPane.WARNING_MESSAGE);
    }
    private void periodebayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodebayarActionPerformed
         
    }//GEN-LAST:event_periodebayarActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        if (ac.isSelected()==true ){

        }
    }//GEN-LAST:event_acActionPerformed

    private void tahunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunanActionPerformed
        if (tahunan.isSelected() ==true){
            pilih = 1;
            periodebayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{ "~~~Silahkan Pilih~~~","1 Tahun","2 Tahun","3 Tahun"}));
        }                                        
    }//GEN-LAST:event_tahunanActionPerformed

    private void magiccomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magiccomActionPerformed
        if (magiccom.isSelected() ==true){
        } 
    }//GEN-LAST:event_magiccomActionPerformed

    private void televisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_televisiActionPerformed
        if (televisi.isSelected() ==true){
        } 
    }//GEN-LAST:event_televisiActionPerformed

    private void dispenserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispenserActionPerformed
        if (dispenser.isSelected() ==true){
        } 
    }//GEN-LAST:event_dispenserActionPerformed

    private void kipasanginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kipasanginActionPerformed
        if (kipasangin.isSelected() ==true){
        } 
    }//GEN-LAST:event_kipasanginActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        jumlah.setText("");     
        jumlah.setEditable(false);
        namapenyewa.setEditable(false);
        namapenyewa.setText("");
        alamatpenyewa.setEditable(false);
        alamatpenyewa.setText("");
        bulanan.setSelected(false);
        tahunan.setSelected(false);
        periodebayar.setSelectedIndex(0);
        ac.setSelected(false);
        televisi.setSelected(false);
        dispenser.setSelected(false);
        kipasangin.setSelected(false);
        magiccom.setSelected(false);
    }//GEN-LAST:event_btnnewActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        int hrgsewa =0, total = 0, hrgfac=0,hrgfmc=0, hrgftv=0, hrgfdp=0, hrgfka=0;
        if(namapenyewa.getText().length()==0){
            pesankosong();
        }
        if (alamatpenyewa.getText().length()==0){
            pesankosong();
        }
        if (pilih ==1){
           if(periodebayar.getSelectedIndex()==1){
               hrgsewa= 300000*12;
               total= total+hrgsewa;
               if (ac.isSelected()==true){
                   hrgfac=100000;
                   total = total+hrgfac;
               }
               if (magiccom.isSelected()==true){
                   hrgfmc=90000;
                   total = total+hrgfmc;
               }
               if (televisi.isSelected()==true){
                   hrgftv=80000;
                   total = total+hrgftv;
               }
               if (dispenser.isSelected()==true){
                   hrgfdp=70000;
                   total = total+hrgfdp;
               }
               if (kipasangin.isSelected()==true){
                   hrgfka=60000;
                   total = total+hrgfka;
           }  
        }
           if (periodebayar.getSelectedIndex()==2){
               hrgsewa=300000*24;
               total=total+hrgsewa;
           if (ac.isSelected()==true){
               hrgfac=100000;
               total=total+hrgfac;
           }
           if (magiccom.isSelected()==true){
               hrgfmc=90000;
               total=total+hrgfmc;
           }     
            if (televisi.isSelected()==true){
               hrgftv=80000;
               total=total+hrgftv;
            }    
            if (dispenser.isSelected()==true){
               hrgfdp=70000;
               total=total+hrgfdp;
            }
            if (kipasangin.isSelected()==true){
               hrgfka=60000;
               total=total+hrgfka;
           }
           }
       if (periodebayar.getSelectedIndex()==3){
           hrgsewa = 300000*36;
           total=total+hrgsewa;
           
           if (ac.isSelected()==true){
               hrgfac=100000;
               total=total+hrgfac;
           }     
           if (magiccom.isSelected()==true){
               hrgfmc=90000;
               total=total+hrgfmc;
           }
          
            if (televisi.isSelected()==true){
               hrgftv=80000;
               total=total+hrgftv;
            }
            if (dispenser.isSelected()==true){
               hrgfdp=70000;
               total=total+hrgfdp;
            }
            if (kipasangin.isSelected()==true){
               hrgfka=60000;
               total=total+hrgfka;
            }
            }
       }
        
        if (pilih == 2){
            if (periodebayar.getSelectedIndex()==1){
                hrgsewa=300000*1;
                total=total+hrgsewa;
                
                if (ac.isSelected()==true){
               hrgfac=100000;
               total=total+hrgfac;
           }     
           if (magiccom.isSelected()==true){
               hrgfmc=90000;
               total=total+hrgfmc;
           }
          
            if (televisi.isSelected()==true){
               hrgftv=80000;
               total=total+hrgftv;
            }
            if (dispenser.isSelected()==true){
               hrgfdp=70000;
               total=total+hrgfdp;
            }
            if (kipasangin.isSelected()==true){
               hrgfka=60000;
               total=total+hrgfka;
            
            }
        }
            if (periodebayar.getSelectedIndex()==2){
                hrgsewa=300000*3;
                total=total+hrgsewa;
                
                if (ac.isSelected()==true){
               hrgfac=100000;
               total=total+hrgfac;
           }     
           if (magiccom.isSelected()==true){
               hrgfmc=90000;
               total=total+hrgfmc;
           }
          
            if (televisi.isSelected()==true){
               hrgftv=80000;
               total=total+hrgftv;
            }
            if (dispenser.isSelected()==true){
               hrgfdp=70000;
               total=total+hrgfdp;
            }
            if (kipasangin.isSelected()==true){
               hrgfka=60000;
               total=total+hrgfka;
            }
            }
            if (periodebayar.getSelectedIndex()==3){
                hrgsewa=300000*6;
                total=total+hrgsewa;
                
                if (ac.isSelected()==true){
               hrgfac=100000;
               total=total+hrgfac;
           }     
           if (magiccom.isSelected()==true){
               hrgfmc=90000;
               total=total+hrgfmc;
           }
          
            if (televisi.isSelected()==true){
               hrgftv=80000;
               total=total+hrgftv;
            }
            if (dispenser.isSelected()==true){
               hrgfdp=70000;
               total=total+hrgfdp;
            }
            if (kipasangin.isSelected()==true){
               hrgfka=60000;
               total=total+hrgfka;
            }
            }
        }
        
        ttlbayar=total;
        jumlah.setText("Rp."+""+ttlbayar+",-");
    }//GEN-LAST:event_btntotalActionPerformed

    private void namapenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapenyewaActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sewakamarwahyudi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sewakamarwahyudi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sewakamarwahyudi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sewakamarwahyudi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sewakamarwahyudi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ac;
    private javax.swing.JTextField alamatpenyewa;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btntotal;
    private javax.swing.JRadioButton bulanan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox dispenser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JCheckBox kipasangin;
    private javax.swing.JCheckBox magiccom;
    private javax.swing.JTextField namapenyewa;
    private javax.swing.JComboBox periodebayar;
    private javax.swing.JRadioButton tahunan;
    private javax.swing.JCheckBox televisi;
    // End of variables declaration//GEN-END:variables
}
